on: push

jobs:
  macos-xcode:
    runs-on: macos-latest
    steps:
      - name: "Print current version of Xcode"
        run: xcodebuild -version
      # - uses: sinoru/actions-setup-xcode@v1.1
      #   with:
      #     xcode-version: '12.0'
      # - run: xcodebuild -version
