on: push

jobs:
  macos-xcode:
    runs-on: macos-latest
    steps:
      - uses: actions/checkout@master
      - uses: sinoru/actions-setup-xcode@v1.1
        with:
          xcode-version: '12.0'
      - run: xcodebuild -version
